# Generated by Django 2.2.7 on 2019-11-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0002_auto_20191120_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_credentials',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
