# Generated by Django 2.2.7 on 2019-11-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0003_employee_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=10)),
                ('mobile_no', models.IntegerField()),
                ('address_1', models.CharField(max_length=80)),
                ('address_2', models.CharField(max_length=80)),
                ('pan_card', models.CharField(max_length=20)),
                ('aadhar_no', models.IntegerField()),
                ('dob', models.DateField()),
                ('photo', models.ImageField(height_field='100px', upload_to='images', width_field='100px')),
            ],
        ),
        migrations.DeleteModel(
            name='employee_credentials',
        ),
    ]
