# Generated by Django 2.2.7 on 2019-11-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0004_auto_20191125_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
