# Generated by Django 2.2.7 on 2019-11-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0005_auto_20191125_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_leaves_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('leave_type', models.CharField(max_length=30)),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('applied_date', models.DateField()),
                ('status', models.CharField(default='NA', max_length=5)),
            ],
        ),
    ]
