# Generated by Django 2.2.7 on 2019-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0007_employee_leaves_details_leave_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('total_eligible_leaves', models.IntegerField(default=24)),
                ('leaves_taken', models.IntegerField(default=0)),
                ('remaining_leaves', models.IntegerField(default=0)),
            ],
        ),
    ]
