# Generated by Django 2.2.7 on 2019-12-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0008_leave_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=10)),
                ('mobile_no', models.IntegerField()),
                ('address_1', models.CharField(max_length=80)),
                ('address_2', models.CharField(max_length=80)),
                ('pan_card', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('dept_code', models.CharField(max_length=20)),
                ('aadhar_no', models.IntegerField()),
                ('dob', models.DateField()),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='admin_credentials',
        ),
    ]
