# Generated by Django 2.2.7 on 2019-12-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0009_auto_20191203_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leaves_details',
            name='comments',
            field=models.CharField(default='', max_length=200),
        ),
    ]
