# Generated by Django 2.2.7 on 2019-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management_system', '0012_auto_20191205_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_info',
            name='status',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
